### PR TITLE
remove HOST_PREFIX/CROSS_COMPILE naming for ldr

### PR DESCRIPTION
**Pull request by twoerner**
The upstream U-Boot Makefile contains the line:

	$(CROSS_COMPILE)ldr

for calling the ldr program in order to generate the required boot stream for booting from an sc5xx's bootrom. This is the exact same prefix string that is used by gcc's suite of tools. This prefix depends on the target architecture, distribution, OS, and ABI calling convention. E.g. arm-poky-linux-gnueabi-ldr.

This works when builds are run with these exact assumptions, but if anything changes, the compile step of u-boot-adi will fail:

	| arm-oe-linux-gnueabi-ldr -T "ADSP-SC589-0.1" -c u-boot.ldr u-boot --bcode=1 --use-vmas
	| /bin/sh: arm-oe-linux-gnueabi-ldr: command not found

Fix this issue in a generic way so that it works for all situations.

Specifically in the ldr-adi-native recipe do not install the ldr utility with a prefix. Also, in the u-boot-adi recipe, set an environment variable when building to ignore the $(CROSS_COMPILE) component when looking for the ldr tool.

Signed-off-by: Trevor Woerner <twoerner@gmail.com>

### CODE REVIEW

**Comment by twoerner** [comment]
hold on, adsp-boot is failing, it needs an ldr tweak
give me a moment... i'll need to update this patch

**Comment by twoerner** [comment]
okay, updated.
ready for testing/review

**Review by timesys-nathan — APPROVED** [review]
Merged internally, commit will make it upstream during next sync up

**Comment by timesys-nathan** [comment]
> This is so frustrating.
> 
> I've sent emails explaining why hard-coding the $(CROSS_COMPILE) string is wrong. We've discussed this at length. I thought we were all in agreement.
> 
> I've sent multiple patches at various times for various branches hoping that eventually one of them will land. None of these patches affects your work. I'm not "fixing" things for me and "breaking" things for everyone else. My patches make everything work for everyone, not just your one simple case. Yet every time my patches are closed without applying them.
> 
> Why?

As I stated earlier, this commit was already merged internally.  I believe he's just closing it for that reason.

**Comment by vasbimpikasadi** [comment]
Sorry this all on me. I'm reverting some other commits I made in error and I had to delete and reinstate the branch as the quickest solution. The PR closing was just a side-effect, not intentional.

**Comment by twoerner** [comment]
Okay, sounds good. The huge push earlier looked like you were syncing your internal to github, but I'm glad to hear there's more to come. Thanks for the update.

I'll fix the merge conflict and re-push.

**Comment by vasbimpikasadi** [comment]
That's now merged from the internal repo: https://github.com/analogdevicesinc/lnxdsp-adi-meta/commit/b6bdd6367b62e762aca3e66cd9fdf77c1b715335

Sorry for the confusion!

**Pull request closed without merging**
